### PR TITLE
Hide branch name when "# Branches per tile" is 0

### PR DESCRIPTION
**Pull request by LazyTarget**
For a minimalistic build status

### CODE REVIEW

**Comment by amoerie** [comment]
The change looks simple, but how exactly is this useful? You just want to see if the default branch fails?

**Comment by LazyTarget** [comment]
Exactly!
In my case I have three build configurations, only the first one has multiple branches. With this change they could be of the same size. Especially since I only care about the default branch

**Comment by amoerie** [comment]
Sounds good, thanks for your contributions!  I’ll add your name to the very exclusive contributors list! :wink:

**Comment by Sharken03** [comment]
I think that with Git as VCS this makes sense. When using Mercurial with 2019.1, it will be possible to have builds without a Default Branch, which is the direction we are going.

**Comment by LazyTarget** [comment]
@Sharken03 I believe this is something towards the application in general. @amoerie Correct me if I am wrong, but currently the application gets branches and prioritizing those where IsDefault is set. If None are set, then it still returns those that are not. This commit is independent of the IsDefault flag.

I believe you are in need of a config that determines which branch(es) you want to display. This should be discussed outside of this pull request

**Comment by amoerie** [comment]
In the latest version of TeamCityTheatre, you can customize the API query to TeamCity that fetches the builds. Not sure if you'll be able to do exactly what you want (e.g. only fetch a few branches), but it might be helpful. I can imagine you might want to customize this for each dashboard/tile too, so that complicates things.

**Pull request merged**
