### PR TITLE
Test numbers and minor CSS change for branch name

### PR DESCRIPTION
**Pull request by bharaba**
Original solution didn't provide test counts. Branch name was too big.

### CODE REVIEW

**Comment by amoerie** [comment]
Nice work! I'll have to check this out on my next chunk of free time. I'm a little worried about smaller branch names and more information on the tiles though.

I'll get back to you!

**Comment by bharaba** [comment]
Sure thing ;-)

Sorry about the look of the pull. A lot of the touched files are just reformatted by VS.

Cheers,
Dobri

**Comment by amoerie** [comment]
I'm sorry, but after testing your PR here on our systems, the fonts are way too small and the branch names are barely readable. I'm afraid I'll have to close this PR.

The first and most important information on a tile is still the branch names, which are way too small due to your CSS changes.

Thanks for your contribution though, I really liked the idea but there's only a limited amount of screenspace.

**Comment by bharaba** [comment]
No worries, cheers!

On Jul 26, 2016, at 3:00 AM, Alexander Moerman <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm sorry, but after testing your PR here on our systems, the fonts are way too small and the branch names are barely readable. I'm afraid I'll have to close this PR.

The first and most important information on a tile is still the branch names, which are way too small due to your CSS changes.

Thanks for your contribution though, I really liked the idea but there's only a limited amount of screenspace.

-

**Pull request closed without merging**
